### ISSUE TITLE
Super long list of networks

### ISSUE THREAD

**Issue by Lejving** [spencersutton/advanced-logistics-system#2]
http://i.imgur.com/f0DvIoe.png

I have 56 networks so not an error the amount, I just can't seem to be able to close it in any way since I can't reach the button.

**Comment by spencersutton** [comment]
Commit f7b34fa60e44783207c7f74ce52bb72b2f09b31a closes #2

**Comment by anoutsider** [comment]
Thanks spencersutton for stepping up and saving the mod while i was away :)

I had alot of updates added to the mod about a month ago, so i couldn't merge your commits without alot of conflicts headache, i did follow a similar approach and also added a search field to the list.

**Comment by spencersutton** [comment]
Glad to see that you're back, your 0.3 update looks nice. Making the fixes was a good exercise for me to learn Factorio modding.
